# Generated by Django 3.0 on 2023-02-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20230214_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
